root /app/.output/public;

location = /sw.js {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    try_files $uri =404;
}

location = /manifest.webmanifest {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    default_type application/manifest+json;
    try_files $uri =404;
}

location = /inject-sw.js {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    try_files $uri =404;
}

location ^~ /_nuxt/ {
    add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable";
    try_files $uri =404;
}

location ^~ /workbox- {
    add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable";
    try_files $uri =404;
}

location ~* \.js$ {
    add_header Cache-Control "public, max-age=0, s-maxage=0, must-revalidate" always;
    try_files $uri =404;
}

location / {
  autoindex off;
  port_in_redirect off;
  expires off;
  add_header Cache-Control "public, max-age=0, s-maxage=0, must-revalidate" always;
  include mime.types;
  types {
    application/manifest+json  webmanifest;
  }
  try_files $uri $uri/ /index.html =404;
}
