import { MigrationInterface, QueryRunner } from 'typeorm';

export class ZonePublication1785518400000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication" (
        "id" uuid NOT NULL,
        "revision" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "sourceRevision" bigint NOT NULL,
        "materializationVersion" integer NOT NULL DEFAULT 1,
        "status" character varying(20) NOT NULL,
        "sourceComputedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "zoneCount" integer NOT NULL DEFAULT 0,
        "communeLinkCount" integer NOT NULL DEFAULT 0,
        "geojsonUrl" text,
        "geojsonChecksum" character varying(64),
        "pmtilesUrl" text,
        "pmtilesChecksum" character varying(64),
        "validationError" text,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "validatedAt" TIMESTAMP WITH TIME ZONE,
        "candidateAt" TIMESTAMP WITH TIME ZONE,
        "activatedAt" TIMESTAMP WITH TIME ZONE,
        "failedAt" TIMESTAMP WITH TIME ZONE,
        "legacyPromotedAt" TIMESTAMP WITH TIME ZONE,
        "dataGouvPromotedAt" TIMESTAMP WITH TIME ZONE,
        "promotionLastAttemptAt" TIMESTAMP WITH TIME ZONE,
        "promotionError" text,
        CONSTRAINT "PK_zone_publication" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_zone_publication_revision" UNIQUE ("revision"),
        CONSTRAINT "CHK_zone_publication_status" CHECK (
          "status" IN (
            'building', 'validated', 'candidate', 'active', 'retired',
            'superseded', 'failed'
          )
        )
      )
    `);
    await queryRunner.query(`
      ALTER TABLE "zone_publication"
      ADD COLUMN IF NOT EXISTS "materializationVersion" integer NOT NULL DEFAULT 1
    `);
    await queryRunner.query(`
      ALTER TABLE "zone_publication"
      ADD COLUMN IF NOT EXISTS "legacyPromotedAt" TIMESTAMP WITH TIME ZONE,
      ADD COLUMN IF NOT EXISTS "dataGouvPromotedAt" TIMESTAMP WITH TIME ZONE,
      ADD COLUMN IF NOT EXISTS "promotionLastAttemptAt" TIMESTAMP WITH TIME ZONE,
      ADD COLUMN IF NOT EXISTS "promotionError" text
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication_zone" (
        "id" BIGSERIAL NOT NULL,
        "publicationId" uuid NOT NULL,
        "sourceZoneId" integer NOT NULL,
        "departmentId" integer NOT NULL,
        "departmentCode" character varying(3) NOT NULL,
        "type" character varying(3) NOT NULL,
        "geom" geometry NOT NULL,
        "publicPayload" jsonb NOT NULL,
        CONSTRAINT "PK_zone_publication_zone" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_zone_publication_zone_source"
          UNIQUE ("publicationId", "sourceZoneId"),
        CONSTRAINT "UQ_zone_publication_zone_identity"
          UNIQUE ("id", "publicationId"),
        CONSTRAINT "CHK_zone_publication_zone_type"
          CHECK ("type" IN ('SOU', 'SUP', 'AEP')),
        CONSTRAINT "FK_zone_publication_zone_publication"
          FOREIGN KEY ("publicationId") REFERENCES "zone_publication"("id")
          ON DELETE CASCADE,
        CONSTRAINT "FK_zone_publication_zone_department"
          FOREIGN KEY ("departmentId") REFERENCES "departement"("id")
          ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_zone_publication"
      ON "zone_publication_zone" ("publicationId")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_zone_department"
      ON "zone_publication_zone" ("departmentId")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_zone_geom"
      ON "zone_publication_zone" USING GIST ("geom")
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication_commune" (
        "publicationZoneId" bigint NOT NULL,
        "communeId" integer NOT NULL,
        "publicationId" uuid NOT NULL,
        "communeCode" character varying(6) NOT NULL,
        CONSTRAINT "PK_zone_publication_commune"
          PRIMARY KEY ("publicationZoneId", "communeId"),
        CONSTRAINT "FK_zone_publication_commune_zone"
          FOREIGN KEY ("publicationZoneId", "publicationId")
          REFERENCES "zone_publication_zone"("id", "publicationId")
          ON DELETE CASCADE,
        CONSTRAINT "FK_zone_publication_commune_commune"
          FOREIGN KEY ("communeId") REFERENCES "commune"("id")
          ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_commune_publication"
      ON "zone_publication_commune" ("publicationId")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_commune_code"
      ON "zone_publication_commune" ("publicationId", "communeCode")
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication_state" (
        "id" integer NOT NULL DEFAULT 1,
        "activePublicationId" uuid,
        "candidatePublicationId" uuid,
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_zone_publication_state" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_zone_publication_state_singleton" CHECK ("id" = 1),
        CONSTRAINT "FK_zone_publication_state_active"
          FOREIGN KEY ("activePublicationId") REFERENCES "zone_publication"("id")
          ON DELETE SET NULL,
        CONSTRAINT "FK_zone_publication_state_candidate"
          FOREIGN KEY ("candidatePublicationId") REFERENCES "zone_publication"("id")
          ON DELETE SET NULL
      )
    `);
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication_instance" (
        "instanceId" character varying(200) NOT NULL,
        "activePublicationId" uuid,
        "candidatePublicationId" uuid,
        "zoneCount" integer,
        "communeLinkCount" integer,
        "lastError" text,
        "heartbeatAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_zone_publication_instance" PRIMARY KEY ("instanceId"),
        CONSTRAINT "FK_zone_publication_instance_active"
          FOREIGN KEY ("activePublicationId") REFERENCES "zone_publication"("id")
          ON DELETE SET NULL,
        CONSTRAINT "FK_zone_publication_instance_candidate"
          FOREIGN KEY ("candidatePublicationId") REFERENCES "zone_publication"("id")
          ON DELETE SET NULL
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_zone_publication_instance_heartbeat"
      ON "zone_publication_instance" ("heartbeatAt")
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "zone_publication_source_state" (
        "id" integer NOT NULL DEFAULT 1,
        "revision" bigint NOT NULL DEFAULT 0,
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_zone_publication_source_state" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_zone_publication_source_state_singleton"
          CHECK ("id" = 1)
      )
    `);
    const keyConstraints = [
      {
        name: 'PK_zone_publication',
        table: 'zone_publication',
        type: 'p',
        columns: ['id'],
        definition: 'PRIMARY KEY ("id")',
      },
      {
        name: 'UQ_zone_publication_revision',
        table: 'zone_publication',
        type: 'u',
        columns: ['revision'],
        definition: 'UNIQUE ("revision")',
      },
      {
        name: 'PK_zone_publication_zone',
        table: 'zone_publication_zone',
        type: 'p',
        columns: ['id'],
        definition: 'PRIMARY KEY ("id")',
      },
      {
        name: 'UQ_zone_publication_zone_source',
        table: 'zone_publication_zone',
        type: 'u',
        columns: ['publicationId', 'sourceZoneId'],
        definition: 'UNIQUE ("publicationId", "sourceZoneId")',
      },
      {
        name: 'UQ_zone_publication_zone_identity',
        table: 'zone_publication_zone',
        type: 'u',
        columns: ['id', 'publicationId'],
        definition: 'UNIQUE ("id", "publicationId")',
      },
      {
        name: 'PK_zone_publication_commune',
        table: 'zone_publication_commune',
        type: 'p',
        columns: ['publicationZoneId', 'communeId'],
        definition: 'PRIMARY KEY ("publicationZoneId", "communeId")',
      },
      {
        name: 'PK_zone_publication_state',
        table: 'zone_publication_state',
        type: 'p',
        columns: ['id'],
        definition: 'PRIMARY KEY ("id")',
      },
      {
        name: 'PK_zone_publication_instance',
        table: 'zone_publication_instance',
        type: 'p',
        columns: ['instanceId'],
        definition: 'PRIMARY KEY ("instanceId")',
      },
      {
        name: 'PK_zone_publication_source_state',
        table: 'zone_publication_source_state',
        type: 'p',
        columns: ['id'],
        definition: 'PRIMARY KEY ("id")',
      },
    ];
    for (const constraint of keyConstraints) {
      const columns = constraint.columns
        .map((column) => `'${column}'`)
        .join(', ');
      await queryRunner.query(`
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint existing_constraint
            WHERE existing_constraint.conrelid = '"${constraint.table}"'::regclass
              AND existing_constraint.contype = '${constraint.type}'
              AND (
                SELECT array_agg(
                  attribute.attname::text ORDER BY key_column.ordinality
                )
                FROM unnest(existing_constraint.conkey) WITH ORDINALITY
                  AS key_column(attnum, ordinality)
                INNER JOIN pg_attribute attribute
                  ON attribute.attrelid = existing_constraint.conrelid
                  AND attribute.attnum = key_column.attnum
              ) = ARRAY[${columns}]::text[]
          ) THEN
            ALTER TABLE "${constraint.table}"
            ADD CONSTRAINT "${constraint.name}" ${constraint.definition};
          END IF;
        END
        $$
      `);
    }

    const checkConstraints = [
      {
        name: 'CHK_zone_publication_status',
        table: 'zone_publication',
        definition: `CHECK (
          "status" IN (
            'building', 'validated', 'candidate', 'active', 'retired',
            'superseded', 'failed'
          )
        )`,
      },
      {
        name: 'CHK_zone_publication_zone_type',
        table: 'zone_publication_zone',
        definition: `CHECK ("type" IN ('SOU', 'SUP', 'AEP'))`,
      },
      {
        name: 'CHK_zone_publication_state_singleton',
        table: 'zone_publication_state',
        definition: `CHECK ("id" = 1)`,
      },
      {
        name: 'CHK_zone_publication_source_state_singleton',
        table: 'zone_publication_source_state',
        definition: `CHECK ("id" = 1)`,
      },
    ];
    for (const constraint of checkConstraints) {
      await queryRunner.query(`
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = '${constraint.name}'
              AND conrelid = '"${constraint.table}"'::regclass
          ) THEN
            ALTER TABLE "${constraint.table}"
            ADD CONSTRAINT "${constraint.name}"
            ${constraint.definition} NOT VALID;
          END IF;
        END
        $$
      `);
      await queryRunner.query(`
        ALTER TABLE "${constraint.table}"
        VALIDATE CONSTRAINT "${constraint.name}"
      `);
    }

    await queryRunner.query(`
      INSERT INTO "zone_publication_state" ("id") VALUES (1)
      ON CONFLICT ("id") DO NOTHING
    `);
    await queryRunner.query(`
      INSERT INTO "zone_publication_source_state" ("id") VALUES (1)
      ON CONFLICT ("id") DO NOTHING
    `);

    const foreignKeys = [
      {
        name: 'FK_zone_publication_zone_publication',
        table: 'zone_publication_zone',
        definition:
          'FOREIGN KEY ("publicationId") REFERENCES "zone_publication"("id") ON DELETE CASCADE',
      },
      {
        name: 'FK_zone_publication_zone_department',
        table: 'zone_publication_zone',
        definition:
          'FOREIGN KEY ("departmentId") REFERENCES "departement"("id") ON DELETE RESTRICT',
      },
      {
        name: 'FK_zone_publication_commune_zone',
        table: 'zone_publication_commune',
        definition:
          'FOREIGN KEY ("publicationZoneId", "publicationId") REFERENCES "zone_publication_zone"("id", "publicationId") ON DELETE CASCADE',
      },
      {
        name: 'FK_zone_publication_commune_commune',
        table: 'zone_publication_commune',
        definition:
          'FOREIGN KEY ("communeId") REFERENCES "commune"("id") ON DELETE RESTRICT',
      },
      {
        name: 'FK_zone_publication_state_active',
        table: 'zone_publication_state',
        definition:
          'FOREIGN KEY ("activePublicationId") REFERENCES "zone_publication"("id") ON DELETE SET NULL',
      },
      {
        name: 'FK_zone_publication_state_candidate',
        table: 'zone_publication_state',
        definition:
          'FOREIGN KEY ("candidatePublicationId") REFERENCES "zone_publication"("id") ON DELETE SET NULL',
      },
      {
        name: 'FK_zone_publication_instance_active',
        table: 'zone_publication_instance',
        definition:
          'FOREIGN KEY ("activePublicationId") REFERENCES "zone_publication"("id") ON DELETE SET NULL',
      },
      {
        name: 'FK_zone_publication_instance_candidate',
        table: 'zone_publication_instance',
        definition:
          'FOREIGN KEY ("candidatePublicationId") REFERENCES "zone_publication"("id") ON DELETE SET NULL',
      },
    ];
    for (const foreignKey of foreignKeys) {
      await queryRunner.query(`
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = '${foreignKey.name}'
              AND conrelid = '"${foreignKey.table}"'::regclass
          ) THEN
            ALTER TABLE "${foreignKey.table}"
            ADD CONSTRAINT "${foreignKey.name}"
            ${foreignKey.definition} NOT VALID;
          END IF;
        END
        $$
      `);
      await queryRunner.query(`
        ALTER TABLE "${foreignKey.table}"
        VALIDATE CONSTRAINT "${foreignKey.name}"
      `);
    }

    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION bump_zone_publication_source_revision()
      RETURNS trigger AS $$
      BEGIN
        UPDATE "zone_publication_source_state"
        SET "revision" = "revision" + 1, "updatedAt" = now()
        WHERE "id" = 1;
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    `);

    const sourceTables = [
      'zone_alerte',
      'restriction',
      'usage',
      'arrete_restriction',
      'arrete_cadre',
      'fichier',
      'thematique',
      'parametres',
      'commune',
      'departement',
      'bassin_versant',
      'arrete_cadre_zone_alerte_communes',
      'ac_za_communes',
      'arrete_cadre_arrete_restriction',
      'arrete_cadre_departement',
      'arrete_cadre_zone_alerte',
      'restriction_commune',
      'bassin_versant_departement',
      'sandre_zone_alias',
    ];
    for (const table of sourceTables) {
      await queryRunner.query(`
        CREATE TRIGGER "TRG_${table}_zone_publication_revision"
        AFTER INSERT OR UPDATE OR DELETE ON "${table}"
        FOR EACH STATEMENT EXECUTE FUNCTION bump_zone_publication_source_revision()
      `);
    }

    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION enforce_zone_publication_content_immutable()
      RETURNS trigger AS $$
      DECLARE
        old_publication_status character varying;
        new_publication_status character varying;
      BEGIN
        IF TG_OP = 'INSERT' THEN
          SELECT "status" INTO new_publication_status
          FROM "zone_publication"
          WHERE "id" = NEW."publicationId";

          IF new_publication_status IS DISTINCT FROM 'building' THEN
            RAISE EXCEPTION 'Publication % content is immutable in status %',
              NEW."publicationId", new_publication_status;
          END IF;
          RETURN NEW;
        END IF;

        IF TG_OP = 'DELETE' THEN
          SELECT "status" INTO old_publication_status
          FROM "zone_publication"
          WHERE "id" = OLD."publicationId";

          IF old_publication_status IN ('validated', 'candidate', 'active') THEN
            RAISE EXCEPTION 'Cannot delete content from % publication %',
              old_publication_status, OLD."publicationId";
          END IF;
          RETURN OLD;
        END IF;

        SELECT "status" INTO old_publication_status
        FROM "zone_publication"
        WHERE "id" = OLD."publicationId";
        SELECT "status" INTO new_publication_status
        FROM "zone_publication"
        WHERE "id" = NEW."publicationId";

        IF OLD."publicationId" IS DISTINCT FROM NEW."publicationId" THEN
          RAISE EXCEPTION 'Publication content cannot move between publications';
        END IF;
        IF old_publication_status IS DISTINCT FROM 'building'
          OR new_publication_status IS DISTINCT FROM 'building' THEN
          RAISE EXCEPTION 'Publication % content is immutable in status %',
            OLD."publicationId", old_publication_status;
        END IF;
        IF TG_TABLE_NAME = 'zone_publication_zone' AND (
          OLD."id" IS DISTINCT FROM NEW."id"
          OR OLD."sourceZoneId" IS DISTINCT FROM NEW."sourceZoneId"
        ) THEN
          RAISE EXCEPTION 'Zone publication identity cannot be modified';
        END IF;
        IF TG_TABLE_NAME = 'zone_publication_commune' AND (
          OLD."publicationZoneId" IS DISTINCT FROM NEW."publicationZoneId"
          OR OLD."communeId" IS DISTINCT FROM NEW."communeId"
          OR OLD."communeCode" IS DISTINCT FROM NEW."communeCode"
        ) THEN
          RAISE EXCEPTION 'Commune publication identity cannot be modified';
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);
    await queryRunner.query(`
      CREATE TRIGGER "TRG_zone_publication_zone_immutable"
      BEFORE INSERT OR UPDATE OR DELETE ON "zone_publication_zone"
      FOR EACH ROW EXECUTE FUNCTION enforce_zone_publication_content_immutable()
    `);
    await queryRunner.query(`
      CREATE TRIGGER "TRG_zone_publication_commune_immutable"
      BEFORE INSERT OR UPDATE OR DELETE ON "zone_publication_commune"
      FOR EACH ROW EXECUTE FUNCTION enforce_zone_publication_content_immutable()
    `);
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION enforce_zone_publication_metadata_immutable()
      RETURNS trigger AS $$
      BEGIN
        IF TG_OP = 'DELETE' THEN
          IF OLD."status" NOT IN ('retired', 'superseded', 'failed') THEN
            RAISE EXCEPTION 'Cannot delete % publication %', OLD."status", OLD."id";
          END IF;
          RETURN OLD;
        END IF;

        IF NEW."status" IS DISTINCT FROM OLD."status" AND NOT (
          (OLD."status" = 'building' AND NEW."status" IN ('validated', 'failed'))
          OR (OLD."status" = 'validated' AND NEW."status" IN ('candidate', 'superseded', 'failed'))
          OR (OLD."status" = 'candidate' AND NEW."status" IN ('active', 'superseded', 'failed'))
          OR (OLD."status" = 'active' AND NEW."status" = 'retired')
          OR (OLD."status" = 'retired' AND NEW."status" = 'active')
        ) THEN
          RAISE EXCEPTION 'Invalid publication status transition from % to %',
            OLD."status", NEW."status";
        END IF;

        IF OLD."status" <> 'building' AND (
          NEW."id" IS DISTINCT FROM OLD."id"
          OR NEW."revision" IS DISTINCT FROM OLD."revision"
          OR NEW."sourceRevision" IS DISTINCT FROM OLD."sourceRevision"
          OR NEW."materializationVersion" IS DISTINCT FROM OLD."materializationVersion"
          OR NEW."sourceComputedAt" IS DISTINCT FROM OLD."sourceComputedAt"
          OR NEW."zoneCount" IS DISTINCT FROM OLD."zoneCount"
          OR NEW."communeLinkCount" IS DISTINCT FROM OLD."communeLinkCount"
          OR NEW."geojsonUrl" IS DISTINCT FROM OLD."geojsonUrl"
          OR NEW."geojsonChecksum" IS DISTINCT FROM OLD."geojsonChecksum"
          OR NEW."pmtilesUrl" IS DISTINCT FROM OLD."pmtilesUrl"
          OR NEW."pmtilesChecksum" IS DISTINCT FROM OLD."pmtilesChecksum"
          OR (
            NEW."validationError" IS DISTINCT FROM OLD."validationError"
            AND NOT (
              NEW."status" = 'failed'
              AND OLD."status" IN ('validated', 'candidate')
            )
          )
          OR NEW."createdAt" IS DISTINCT FROM OLD."createdAt"
          OR NEW."validatedAt" IS DISTINCT FROM OLD."validatedAt"
          OR (
            NEW."candidateAt" IS DISTINCT FROM OLD."candidateAt"
            AND NOT (
              OLD."status" = 'validated' AND NEW."status" = 'candidate'
            )
          )
          OR (
            NEW."activatedAt" IS DISTINCT FROM OLD."activatedAt"
            AND NOT (
              NEW."status" = 'active'
              AND OLD."status" IN ('candidate', 'retired')
            )
          )
          OR (
            NEW."failedAt" IS DISTINCT FROM OLD."failedAt"
            AND NOT (
              NEW."status" = 'failed'
              AND OLD."status" IN ('validated', 'candidate')
            )
          )
        ) THEN
          RAISE EXCEPTION 'Publication % metadata is immutable in status %',
            OLD."id", OLD."status";
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);
    await queryRunner.query(`
      CREATE TRIGGER "TRG_zone_publication_metadata_immutable"
      BEFORE UPDATE OR DELETE ON "zone_publication"
      FOR EACH ROW EXECUTE FUNCTION enforce_zone_publication_metadata_immutable()
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const sourceTables = [
      'zone_alerte',
      'restriction',
      'usage',
      'arrete_restriction',
      'arrete_cadre',
      'fichier',
      'thematique',
      'parametres',
      'commune',
      'departement',
      'bassin_versant',
      'arrete_cadre_zone_alerte_communes',
      'ac_za_communes',
      'arrete_cadre_arrete_restriction',
      'arrete_cadre_departement',
      'arrete_cadre_zone_alerte',
      'restriction_commune',
      'bassin_versant_departement',
      'sandre_zone_alias',
    ];
    for (const table of sourceTables) {
      await queryRunner.query(
        `DROP TRIGGER IF EXISTS "TRG_${table}_zone_publication_revision" ON "${table}"`,
      );
    }
    await queryRunner.query(
      `DROP FUNCTION IF EXISTS bump_zone_publication_source_revision`,
    );
    await queryRunner.query(
      `DROP TRIGGER IF EXISTS "TRG_zone_publication_commune_immutable" ON "zone_publication_commune"`,
    );
    await queryRunner.query(
      `DROP TRIGGER IF EXISTS "TRG_zone_publication_zone_immutable" ON "zone_publication_zone"`,
    );
    await queryRunner.query(
      `DROP FUNCTION IF EXISTS enforce_zone_publication_content_immutable`,
    );
    await queryRunner.query(
      `DROP TRIGGER IF EXISTS "TRG_zone_publication_metadata_immutable" ON "zone_publication"`,
    );
    await queryRunner.query(
      `DROP FUNCTION IF EXISTS enforce_zone_publication_metadata_immutable`,
    );
    await queryRunner.query(`DROP TABLE IF EXISTS "zone_publication_instance"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "zone_publication_state"`);
    await queryRunner.query(
      `DROP TABLE IF EXISTS "zone_publication_source_state"`,
    );
    await queryRunner.query(`DROP TABLE IF EXISTS "zone_publication_commune"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "zone_publication_zone"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "zone_publication"`);
  }
}
