import { MigrationInterface, QueryRunner } from 'typeorm';

export class ExternalPublicationRegistry1785604800000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "external_publication_resource" (
        "key" character varying(100) NOT NULL,
        "provider" character varying(40) NOT NULL,
        "remoteResourceId" character varying(255),
        "status" character varying(20) NOT NULL DEFAULT 'configured',
        "sourceDate" date,
        "checksum" character varying(64),
        "byteSize" bigint,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "lastSuccessAt" TIMESTAMP WITH TIME ZONE,
        "lastFailureAt" TIMESTAMP WITH TIME ZONE,
        "lastError" text,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_external_publication_resource" PRIMARY KEY ("key"),
        CONSTRAINT "CHK_external_publication_resource_status" CHECK (
          "status" IN ('configured', 'publishing', 'succeeded', 'failed')
        )
      )
    `);
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "external_publication_run" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "jobKey" character varying(150) NOT NULL,
        "scheduledFor" date NOT NULL,
        "status" character varying(20) NOT NULL,
        "attempt" integer NOT NULL DEFAULT 0,
        "startedAt" TIMESTAMP WITH TIME ZONE,
        "finishedAt" TIMESTAMP WITH TIME ZONE,
        "retryAfter" TIMESTAMP WITH TIME ZONE,
        "error" text,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_external_publication_run" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_external_publication_run_job_date"
          UNIQUE ("jobKey", "scheduledFor"),
        CONSTRAINT "CHK_external_publication_run_status" CHECK (
          "status" IN ('running', 'succeeded', 'failed')
        )
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_external_publication_run_retry"
      ON "external_publication_run" ("status", "retryAfter")
    `);
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "scheduler_heartbeat" (
        "name" character varying(100) NOT NULL,
        "lastSeenAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_scheduler_heartbeat" PRIMARY KEY ("name")
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS "scheduler_heartbeat"');
    await queryRunner.query('DROP TABLE IF EXISTS "external_publication_run"');
    await queryRunner.query(
      'DROP TABLE IF EXISTS "external_publication_resource"',
    );
  }
}
