import type { EquivalenceInput } from './history-source-equivalence';

// Canonical parameter projection of the original certified input anchor.
// Reconstructed read-only on 2026-09-10: only parameter 398.disabled was
// restored in memory to false. The complete 110-row SHA-256 then matched the
// pre-existing 2026-09-08 attestation exactly. No production row was changed.
// These are clipped historical inputs, not a copy of the raw parameter table.
export const CERTIFIED_PARAMETER_ANCHOR_DIGEST =
  'c2313897da371d43b50c0fb39b84629fd0f9c1d7a39713b0d7df08fee2d41633';

export const CERTIFIED_PARAMETER_ANCHOR: readonly EquivalenceInput[] = [
  {
    key: '1',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '25',
  },
  {
    key: '100',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '976',
  },
  {
    key: '101',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '972',
  },
  {
    key: '11',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '70',
  },
  {
    key: '12',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '973',
  },
  {
    key: '143',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '26',
  },
  {
    key: '145',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '2A',
  },
  {
    key: '15',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '02',
  },
  {
    key: '151',
    payload: {
      from: '2026-07-11',
      through: '2026-08-03',
      disabled: true,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '57',
  },
  {
    key: '152',
    payload: {
      from: '2026-07-11',
      through: '2026-07-17',
      disabled: true,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '77',
  },
  {
    key: '16',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '03',
  },
  {
    key: '17',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '04',
  },
  {
    key: '18',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '07',
  },
  {
    key: '19',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '08',
  },
  {
    key: '198',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '14',
  },
  {
    key: '20',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '09',
  },
  {
    key: '204',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '69',
  },
  {
    key: '208',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '58',
  },
  {
    key: '21',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '10',
  },
  {
    key: '211',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '21',
  },
  {
    key: '212',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '87',
  },
  {
    key: '215',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '40',
  },
  {
    key: '221',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '45',
  },
  {
    key: '224',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '13',
  },
  {
    key: '226',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '15',
  },
  {
    key: '228',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '76',
  },
  {
    key: '229',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '43',
  },
  {
    key: '23',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '12',
  },
  {
    key: '26',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '16',
  },
  {
    key: '27',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '17',
  },
  {
    key: '28',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '18',
  },
  {
    key: '29',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '19',
  },
  {
    key: '3',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '59',
  },
  {
    key: '30',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '22',
  },
  {
    key: '301',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '974',
  },
  {
    key: '31',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '27',
  },
  {
    key: '32',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '28',
  },
  {
    key: '33',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '29',
  },
  {
    key: '337',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '66',
  },
  {
    key: '338',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '54',
  },
  {
    key: '35',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '2B',
  },
  {
    key: '36',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '31',
  },
  {
    key: '38',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '35',
  },
  {
    key: '381',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '63',
  },
  {
    key: '383',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '88',
  },
  {
    key: '385',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '78',
  },
  {
    key: '386',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '11',
  },
  {
    key: '387',
    payload: {
      from: '2026-07-11',
      through: '2026-08-03',
      disabled: true,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '34',
  },
  {
    key: '388',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '56',
  },
  {
    key: '389',
    payload: {
      from: '2026-07-11',
      through: '2026-07-16',
      disabled: true,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '47',
  },
  {
    key: '39',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '36',
  },
  {
    key: '390',
    payload: {
      from: '2026-07-16',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '47',
  },
  {
    key: '391',
    payload: {
      from: '2026-07-17',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '77',
  },
  {
    key: '392',
    payload: {
      from: '2026-07-17',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '90',
  },
  {
    key: '393',
    payload: {
      from: '2026-08-03',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '57',
  },
  {
    key: '395',
    payload: {
      from: '2026-08-03',
      through: '2026-08-13',
      disabled: true,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '34',
  },
  {
    key: '396',
    payload: {
      from: '2026-08-04',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '46',
  },
  {
    key: '397',
    payload: {
      from: '2026-08-12',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '72',
  },
  {
    key: '398',
    payload: {
      from: '2026-08-13',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '34',
  },
  {
    key: '40',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '37',
  },
  {
    key: '400',
    payload: {
      from: '2026-08-25',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '38',
  },
  {
    key: '41',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '39',
  },
  {
    key: '43',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '41',
  },
  {
    key: '44',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '42',
  },
  {
    key: '46',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '44',
  },
  {
    key: '48',
    payload: {
      from: '2026-07-11',
      through: '2026-08-04',
      disabled: true,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '46',
  },
  {
    key: '5',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '67',
  },
  {
    key: '50',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '48',
  },
  {
    key: '51',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '49',
  },
  {
    key: '52',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '50',
  },
  {
    key: '53',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '51',
  },
  {
    key: '54',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '52',
  },
  {
    key: '55',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '53',
  },
  {
    key: '57',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '55',
  },
  {
    key: '59',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '62',
  },
  {
    key: '61',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '65',
  },
  {
    key: '62',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '68',
  },
  {
    key: '63',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '71',
  },
  {
    key: '64',
    payload: {
      from: '2026-07-11',
      through: '2026-08-12',
      disabled: true,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '72',
  },
  {
    key: '65',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '73',
  },
  {
    key: '66',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '74',
  },
  {
    key: '67',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '75',
  },
  {
    key: '7',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '80',
  },
  {
    key: '71',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '81',
  },
  {
    key: '72',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '82',
  },
  {
    key: '73',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '85',
  },
  {
    key: '74',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '86',
  },
  {
    key: '77',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_distinct',
    },
    section: 'parameters',
    department: '89',
  },
  {
    key: '78',
    payload: {
      from: '2026-07-11',
      through: '2026-07-17',
      disabled: true,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '90',
  },
  {
    key: '79',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '91',
  },
  {
    key: '8',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '83',
  },
  {
    key: '80',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '92',
  },
  {
    key: '81',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '93',
  },
  {
    key: '82',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '60',
  },
  {
    key: '83',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '64',
  },
  {
    key: '84',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '79',
  },
  {
    key: '85',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '30',
  },
  {
    key: '86',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '24',
  },
  {
    key: '88',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '33',
  },
  {
    key: '89',
    payload: {
      from: '2026-07-11',
      through: '2026-08-25',
      disabled: true,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '38',
  },
  {
    key: '9',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_except_aep',
    },
    section: 'parameters',
    department: '06',
  },
  {
    key: '90',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '05',
  },
  {
    key: '91',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '61',
  },
  {
    key: '92',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '23',
  },
  {
    key: '93',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_only_aep',
    },
    section: 'parameters',
    department: '32',
  },
  {
    key: '95',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '84',
  },
  {
    key: '96',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '01',
  },
  {
    key: '97',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'yes_all',
    },
    section: 'parameters',
    department: '94',
  },
  {
    key: '98',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no',
    },
    section: 'parameters',
    department: '95',
  },
  {
    key: '99',
    payload: {
      from: '2026-07-11',
      through: '2026-08-31',
      disabled: false,
      superpositionCommune: 'no_all',
    },
    section: 'parameters',
    department: '971',
  },
];
